README.md

Message about a new version with performance upgrade and UI overhaul on readme.

Updated README.md on new version

---

README.md

- Updated the readme
- Added badges, website, and discord

PTC-001-Updated-the-readme

---

.github/FUNDING.yml

This PR:
- Adds the funding.yml which allows for sponsorship.

Added funding option

---

README.md
streamlit_app.py
streamlit_second.py

This PR Adds:
- updates the links to the new repository.

Updated the links

---

README.md

This PR Adds: Product Hunt link

Updated with product hunt link

---

.github/ISSUE_TEMPLATE.md

chore: Added issue template for PR's

---

.github/PULL_REQUEST_TEMPLATE.md

chore: added pull request template

---

README.md

Added link to Qdrant 
This PR attributes to the sources used in this project. 
Mentioned Qdrant in the Readme.
- Mentioned Qdrant in the Readme.
Not Applicable

Update Readme add Qdrant Link

---

README.md

- Added a contributors tag in Readme
1. 
2. 
3.

Docs: Add contributor tag in readme

---

CODE_OF_CONDUCT.md

Code of Conduct 
This PR introduces a new file, containing the text of our Code of Conduct. This document outlines the standards of behavior we expect from all participants in our project, whether they are contributors, maintainers, or users. The Code of Conduct aims to foster an open and welcoming environment, free from discrimination, harassment, and toxic behavior.
- Added CODE OF CONDUCT document
1. 
2. 
3.

Docs: add code of conduct

---

.gitignore
archive/resume_matcher.ipynb
requirements.txt

Added a ipynb for the similarity score using cohere and qdrant .
- [ x] Feature Enhancement
- 
- 
- 
1.  Download the notebook and run it locally or in colab
2.  Need to have config.yml file with proper cohere key and qdrant api key and url
3. 
- [x ] The code compiles successfully without any errors or warnings
- [ x] The changes have been tested and verified

added resume matcher ipynb

---

README.md

Click the ‘here’ link in the readme to directly fork this repo
#111 
Updated the 'here' link.
1. click 'here' link in readme
2. navigate to fork page

docs: Click the ‘here’ link in the readme to directly fork this repo

---

README.md
archive/resume_matcher.ipynb
requirements.txt
scripts/similarity/get_similarity_score.py
streamlit_app.py

- [ x] Feature Enhancement
-  Added similarity score code to streamlitapp
-  Included error handling and logging
- 
1. 
2. 
3. 
- [x ] The code compiles successfully without any errors or warnings
- [x ] The documentation has been updated (if applicable)

Added similarity score code to streamlitapp

---

README.md

Updated the Readme with proper links and tech stack changes
Update the badges in the tech stack section. 
- 
- 
- 
1. 
2. 
3.

Fix: updated the readme with pyenv and docs links.

---

streamlit_app.py

modified:   streamlit_app.py
Updated Streamlit descriptions:
- Amended the descriptions of selecting a 'job descriptions'.
It should be job descriptions.
1) Open the streamlit page

Changes to be committed: Updated Streamlit descriptions: - Amended the descriptions of selecting a 'job descriptions'.

---

SECURITY.md

Create a SECURITY.md

---

README.md
webapp/README.md

Add an important note to the README to notify community that the full stack web app currently returns mocked / faked data for the results (e.g. Vector Scores, Common Keyword Matches, Suggestions), and that it will be further developed out and implemented with real results in a later future release.
N/A
- `README.md` - add additional important note relating to mock / fake data results returned within full stack web app.
- `README.md`
Annotated screenshot highlighting the addition to the project `README.md` file.
N/A

chore: update readme notify webapp fake data

---

.gitignore
webapp/app/_components/job-descriptions/add-jobs/add-jobs.tsx
webapp/backend/api/index.py
webapp/backend/scripts/files.py

This feature change allows for user uploaded resumes / CVs and multiple job descriptions to be saved to the local file system as PDF files, within `/Data/Resumes/` and `/Data/JobDescription/` directories respectively.
Every time the user clicks on the `Continue` button on the webapp to begin the resume and job descriptions upload process, then any prior *.local.pdf files will be removed, to avoid unnecessary buildup on files.
The PDF files are suffixed with `*.local.pdf` in the filename to avoid accidental commits / pushes to the main repositories from the community, where this is enforced in the `.gitignore` file as part of this change.
Lastly, a change has been made to the frontend web app UI to temporarily disable (commented out code) the ability to upload job links. The reason is …

feat: web app - save resume and job descs to filesystem

---

requirements.txt
scripts/LinkedinJobToPDF.py

Optimize LinkedIn_to_PDF logic. Preserve Job Description formatting.
N/A
The existing script was not modular and also did not preserve the HTML formatting while scraping job description from LinkedIn.
- Make the script modular
- Preserve HTML formatting
- Name the output PDF file as something meaningful
N/A - Script works as-is. Can be run as a standalone script OR be used in other script in modular way
1. Run pip install -r requirements
2. Run python ./scripts/LinkedinJobToPDF.py
3. Enter LinkedIn Job URL in the pop-up/window prompt
4. Check the Data/JobDescription directory for new PDF file

Feature/Fix: Optimize LinkedIn_to_PDF logic

---

.gitignore

Added `.DS_ignore` to `.gitignore`

Updated .gitignore to ignore .DS_store

---

webapp/app/_components/common-words/common-words.tsx
webapp/app/_components/job-descriptions/add-jobs/add-jobs.tsx
webapp/app/_components/job-descriptions/job-descriptions.tsx
webapp/app/_components/resume/resume-glance/resume-glance.tsx
webapp/app/_components/suggestions/suggestions.tsx
webapp/app/_components/vector-scores/vector-scores.tsx

Changes Made:
- added hover states to buttons
- added similar padding spaces between sub headers
- added rounded borders to subheader sections and subsequent elements
- Made some color changes to improver ui/ux(visibility)
- Other minor fixes

Info section UI enhancement

---

requirements.txt

Fixes the requirements conflict #246 
- 
- 
- 
1. 
2. 
3.

Fix the requirements conflict #246

---

.pre-commit-config.yaml
CONTRIBUTING.md
README.md

Implementation of Pre-commit Hooks and Code Formatting Guidelines
N/A
This pull request introduces pre-commit hooks and code formatting guidelines to enhance code consistency and maintainability. It includes updates to the `contributing.md` and `readme.md` files to provide guidance on using these new features.
- Added pre-commit hooks to automate code formatting and linting before each commit.
- Included code formatting guidelines in `contributing.md` and `readme.md`.
- Updated instructions on how to set up and use pre-commit hooks in the project.
N/A
1. Pull the latest changes from this branch.
2. Ensure that pre-commit hooks are properly configured by attempting to commit changes.
3. Verify that code formatting and linting are automatically applied before each commit.
4. Check …

Add pre-commit hooks and code formatting guidelines

---

run_first.py

Fix directory existence check in `remove_old_files` function
This pull request fixes a bug in the ATS model where the `remove_old_files` function assumed the existence of the directory, which caused an error when the directory was missing. If the directory does not exist, it is now created to prevent errors during file removal.
- Added a check to verify if the directory exists before attempting to list its contents.
- If the directory does not exist, it is created to prevent errors during file removal.
```python
def remove_old_files(files_path):
if not os.path.exists(files_path):
os.makedirs(files_path)
for filename in os.listdir(files_path):
try:
file_path = os.path.join(files_path, filename)
if os.path.isfile(file_path):
os.remove(file_path)
except Exception as e:
logging.error(f"Error …
```

Fix directory existence check in `remove_old_files` function

---

build.dockerfile

Refactor Dockerfile: Reorder COPY and Install Steps for Optimized Layer Caching
No specific issue linked.
This PR refactors the Dockerfile to optimize the layer caching by changing the order of COPY and installation steps. 
This will reduce unnecessary rebuilds when only the application code is modified, improving build efficiency.
Changes Building Time : 150s ->  23s
```bash
- COPY . .
RUN apt-get update
RUN apt-get install -y build-essential python-dev git
RUN pip install -U pip setuptools wheel
- RUN pip install -r requirements.txt
+ COPY requirements.txt requirements.txt
+ RUN pip install -r requirements.txt
+ COPY . .
EXPOSE 8501
RUN python run_first.py
ENTRYPOINT [ "streamlit", "run", "streamlit_app.py"]
```

Reduces build time by 6x

---

requirements.txt
streamlit_app.py
streamlit_interactive.py
streamlit_second.py

Fixes #298 
- Upgrade NLTK dependency to 3.9.1. See https://github.com/nltk/nltk/issues/3308
- Fix breaking change https://github.com/nltk/nltk/issues/3293
1. `docker compose up`
2. Check that the app starts correctly

fix: upgrading nltk dependency to fix wordnet/punkt download

---

app/core/config.py
requirements.txt

Issue 133 v4

---

app/api/middleware.py
app/api/router/v1/resume.py
app/models/association.py
app/models/base.py
app/models/job.py
app/models/resume.py
app/services/resume_service.py

Add pdf parser to markdown capability

---

apps/backend/requirements.txt

Update backend dependency of h11 to 0.16

---

README.es.md

fix: correct translation of "IMPORTANT" in README.es.md
